/*
 * Pure Access REST API
 * REST API Specification for Pure Access/TruCred Integration. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kirill@isonas.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.User;
import io.swagger.client.model.UserUpdate;
import io.swagger.client.model.Users;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Get User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userGETTest() throws ApiException {
        String id = null;
        User response = api.userGET(id);

        // TODO: test validations
    }
    
    /**
     * Update User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userPATCHTest() throws ApiException {
        String id = null;
        UserUpdate user = null;
        User response = api.userPATCH(id, user);

        // TODO: test validations
    }
    
    /**
     * Get All Users
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersGETTest() throws ApiException {
        Users response = api.usersGET();

        // TODO: test validations
    }
    
}
